/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_android_opengl_TestNDK */

#ifndef _Included_com_example_android_opengl_TestNDK
#define _Included_com_example_android_opengl_TestNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    stringTestNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_android_opengl_TestNDK_stringTestNdk
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    stringTestNdk2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_android_opengl_TestNDK_stringTestNdk2
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    verticesArray
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_android_opengl_TestNDK_verticesArray
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    indicesArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_android_opengl_TestNDK_indicesArray
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    indicesSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_android_opengl_TestNDK_indicesSize
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    verticesSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_android_opengl_TestNDK_verticesSize
  (JNIEnv *, jobject);

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    initOcean
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_com_example_android_opengl_TestNDK_initOcean
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    oceanRender
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_example_android_opengl_TestNDK_oceanRender
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
