/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_example_android_opengl_TestNDK */

#ifndef _Included_com_oest_nativeclass_OceanNative
#define _Included_com_oest_nativeclass_OceanNative
#ifdef __cplusplus
extern "C" {
#endif

void initOcean(int N,float A,float Wx,float Wy,float length,float * buffer);
void oceanRender(float t);
float *verticesArray();
unsigned int *indicesArray();
unsigned int indicesSize();
unsigned int verticesCount();
/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    stringTestNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oest_nativeclass_OceanNative_stringTestNdk
  (JNIEnv * env)
{
	return (*env)->NewStringUTF(env, "hhh");
}

/*
 * Class:     com_example_android_opengl_TestNDK
 * Method:    stringTestNdk2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oest_nativeclass_OceanNative_stringTestNdk2
  (JNIEnv * env)
{
	return (*env)->NewStringUTF(env, "hhh");
}

JNIEXPORT jfloatArray JNICALL Java_com_oest_nativeclass_OceanNative_verticesArray
  (JNIEnv *env)
{
	jfloatArray jfa =  (*env)->NewFloatArray(env,verticesCount()*15);
	(*env)->SetFloatArrayRegion(env,jfa ,0, verticesCount()*15 ,verticesArray());
	return jfa;
}

JNIEXPORT jintArray JNICALL Java_com_oest_nativeclass_OceanNative_indicesArray
  (JNIEnv *env)
{
	jintArray ja = (*env)->NewIntArray(env,indicesSize());
	(*env)->SetIntArrayRegion(env,ja,0, indicesSize() ,(const jint *)indicesArray());
	return ja;
}

JNIEXPORT jint JNICALL Java_com_oest_nativeclass_OceanNative_indicesSize
  (JNIEnv *env)
{
	return indicesSize();
}

JNIEXPORT jint JNICALL Java_com_oest_nativeclass_OceanNative_verticesSize
  (JNIEnv * env , jobject obj)
{
	return verticesCount();
}

JNIEXPORT void JNICALL Java_com_oest_nativeclass_OceanNative_initOcean
  (JNIEnv *env,jobject zthis ,jint N,jfloat A,jfloat Wx,jfloat Wy,jfloat length,jobject obj )
{
	float * buffer = (*env)->GetDirectBufferAddress(env, obj);
	initOcean(N,A,Wx,Wy,length,buffer);
}
JNIEXPORT void JNICALL Java_com_oest_nativeclass_OceanNative_oceanRender
  (JNIEnv *env , jobject obj, jfloat t)
{
	oceanRender(t);
}

#ifdef __cplusplus
}
#endif
#endif
